spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    platform: h2
    hikari:
      connection-test-query: SELECT 1
    h2:
      console:
        enabled: true

  jpa:
    database: H2
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    generated-ddl: true
    hibernate:
      ddl-auto: update

  flyway:
    baseline-on-migrate: true
    validate-on-migrate: true